server:
  port: 80

#spring:
#  application:
#    name: cloud-consumer-hystrix-order

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7005.com:7005/eureka/

feign:
  hystrix:
    enable: true